// *** GLOBAL ***
export const SET_GLOBAL_TITLE = "SET_GLOBAL_TITLE";

// *** USER ***
export const SET_USER_AUTHENTICATION = "SET_USER_AUTHENTICATION";
export const SET_USER_PHOTO_URL = "SET_PHOTO_URL";
export const USER_RESET = "USER_RESET";
export const SET_USER_IS_ADMIN = "SET_USER_IS_ADMIN";

// *** NOVO CLIENTE PF ***
export const SET_NOVO_CLIENTE_NOME_COMPLETO = "SET_NOVO_CLIENTE_NOME_COMPLETO";
export const SET_NOVO_CLIENTE_CPF = "SET_NOVO_CLIENTE_CPF";
export const SET_NOVO_CLIENTE_RG = "SET_NOVO_CLIENTE_RG";
export const SET_NOVO_CLIENTE_EMAIL = "SET_NOVO_CLIENTE_EMAILS";
export const SET_NOVO_CLIENTE_TELEFONE = "SET_NOVO_CLIENTE_TELEFONES";
export const SET_NOVO_CLIENTE_PROFISSAO = "SET_NOVO_CLIENTE_PROFISSAO";
export const SET_NOVO_CLIENTE_ESTADO_CIVIL = "SET_NOVO_CLIENTE_ESTADO_CIVIL";
export const SET_NOVO_CLIENTE_REGIME_BENS = "SET_NOVO_CLIENTE_REGIME_BENS";
export const SET_NOVO_CLIENTE_ENDERECO = "SET_NOVO_CLIENTE_ENDERECO";
export const SET_NOVO_CLIENTE_BAIRRO = "SET_NOVO_CLIENTE_BAIRRO";
export const SET_NOVO_CLIENTE_MUNICIPIO = "SET_NOVO_CLIENTE_MUNICIPIO";
export const SET_NOVO_CLIENTE_CEP = "SET_NOVO_CLIENTE_CEP";
export const SET_NOVO_CLIENTE_OBSERVACAO = "SET_NOVO_CLIENTE_OBSERVACAO";
export const RESET_NOVO_CLIENTE = "RESET_NOVO_CLIENTE";