// *** GLOBAL ***
export const SET_GLOBAL_TITLE = "SET_GLOBAL_TITLE";

// *** USER ***
export const USER_RESET = "USER_RESET";
export const SET_USER_IS_ADMIN = "SET_USER_IS_ADMIN";

// *** NOVO VENDEDOR PF ***
export const SET_NOVO_VENDEDOR_NOME_COMPLETO = "SET_NOVO_VENDEDOR_NOME_COMPLETO";
export const SET_NOVO_VENDEDOR_CPF = "SET_NOVO_VENDEDOR_CPF";
export const SET_NOVO_VENDEDOR_RG = "SET_NOVO_VENDEDOR_RG";
export const SET_NOVO_VENDEDOR_EMAIL = "SET_NOVO_VENDEDOR_EMAILS";
export const SET_NOVO_VENDEDOR_TELEFONE = "SET_NOVO_VENDEDOR_TELEFONES";
export const SET_NOVO_VENDEDOR_PROFISSAO = "SET_NOVO_VENDEDOR_PROFISSAO";
export const SET_NOVO_VENDEDOR_ESTADO_CIVIL = "SET_NOVO_VENDEDOR_ESTADO_CIVIL";
export const SET_NOVO_VENDEDOR_REGIME_BENS = "SET_NOVO_VENDEDOR_REGIME_BENS";
export const SET_NOVO_VENDEDOR_LOGRADOURO = "SET_NOVO_VENDEDOR_LOGRADOURO";
export const SET_NOVO_VENDEDOR_NUMERO = "SET_NOVO_VENDEDOR_NUMERO";
export const SET_NOVO_VENDEDOR_COMPLEMENTO = "SET_NOVO_VENDEDOR_COMPLEMENTO";
export const SET_NOVO_VENDEDOR_BAIRRO = "SET_NOVO_VENDEDOR_BAIRRO";
export const SET_NOVO_VENDEDOR_CIDADE = "SET_NOVO_VENDEDOR_CIDADE";
export const SET_NOVO_VENDEDOR_CEP = "SET_NOVO_VENDEDOR_CEP";
export const SET_NOVO_VENDEDOR_OBSERVACAO = "SET_NOVO_VENDEDOR_OBSERVACAO";
export const RESET_NOVO_VENDEDOR = "RESET_NOVO_VENDEDOR";

// *** NOVO CONTRATO ***
export const ADD_NOVO_CONTRATO_VENDEDORES = "SET_NOVO_CONTRATO_VENDEDORES";
export const RESET_NOVO_CONTRATO = "RESET_NOVO_CONTRATO";